#cloud-config
runcmd:
    - /usr/bin/dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    - /usr/bin/dnf update -y
    - /usr/bin/dnf install -y vim-enhanced htop curl wget python3-pip tree nmap-ncat
    - /usr/bin/echo "alias vi=vim" >> ~/.bashrc
    - /usr/bin/chown -R centos.centos /root/
    - /usr/bin/cat /home/centos/.ssh/authorized_keys > /root/.ssh/authorized_keys
    - /usr/bin/chown -R root.root /root/
    - /usr/bin/pip3 install boto boto3 "urllib3<1.24" awscli